//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class home
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public home()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int Id { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> bathrooms { get; set; }
        public Nullable<int> bedrooms { get; set; }
        public string home_location { get; set; }
        public string contact_name { get; set; }
        public string email_contact { get; set; }
        public string phone { get; set; }
        public string home_address { get; set; }
        public string square_feet { get; set; }
        public string year_built { get; set; }
        public string garages { get; set; }
        public string notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
    }
}
